"""Write the generated profile data out for the site to load."""

import datetime
import json
import os

SITE_DIR = "candidate_profiles_site"
DATA_DIR = os.path.join(SITE_DIR, "data")
DATA_FILE = os.path.join(DATA_DIR, "profiles.js")
PAGES = ("index.html", "map.html")

# Both pages must pull the generated file in before their own script block.
EXPECTED_TAG = '<script src="data/profiles.js"></script>'

_BANNER = """\
// Generated by build_profile_site.py - do not edit by hand.
// Source: the roster CSVs at the repository root.
// Built: {built}
// Profiles: {count}
"""


def _atomic_write(path, text):
    """Write *text* to *path* via a temp file so a crash cannot truncate it."""
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    os.replace(tmp, path)


def write_profiles(profiles, stats, root=".", races=None):
    """Emit ``candidate_profiles_site/data/profiles.js``.

    A plain script assignment rather than JSON + ``fetch`` so the pages keep
    working when opened straight off disk - ``file://`` requests are blocked
    by CORS, but ``<script src>`` is not.
    """
    data_dir = os.path.join(root, DATA_DIR)
    os.makedirs(data_dir, exist_ok=True)
    path = os.path.join(root, DATA_FILE)

    # SOURCE_DATE_EPOCH makes the output byte-for-byte reproducible, which is
    # what lets CI assert that a rebuild changes nothing.
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    now = (
        datetime.datetime.fromtimestamp(int(epoch), datetime.timezone.utc)
        if epoch and epoch.isdigit()
        else datetime.datetime.now(datetime.timezone.utc)
    )
    built = now.isoformat(timespec="seconds")
    payload = json.dumps(profiles, ensure_ascii=False, separators=(",", ":"))
    # Defensive: a profile field containing "</script>" would otherwise close
    # the tag early and break the page.
    payload = payload.replace("</script>", "<\\/script>")

    meta = json.dumps(
        {"built": built, "counts": stats}, ensure_ascii=False, separators=(",", ":")
    )
    race_payload = json.dumps(races or [], ensure_ascii=False, separators=(",", ":"))
    race_payload = race_payload.replace("</script>", "<\\/script>")

    text = (
        _BANNER.format(built=built, count=len(profiles))
        + f"window.legislatorsData = {payload};\n"
        + f"window.kycRaces = {race_payload};\n"
        + f"window.kycBuildMeta = {meta};\n"
    )
    _atomic_write(path, text)
    return path, len(text)


def check_pages(root="."):
    """Report which pages are wired up to the generated data file.

    Returns a list of ``(page, ok, note)``.
    """
    results = []
    for page in PAGES:
        path = os.path.join(root, SITE_DIR, page)
        if not os.path.exists(path):
            results.append((page, False, "missing"))
            continue
        with open(path, "r", encoding="utf-8") as handle:
            content = handle.read()
        if EXPECTED_TAG not in content:
            results.append((page, False, "does not load data/profiles.js"))
        elif "window.legislatorsData" not in content:
            results.append((page, False, "does not read window.legislatorsData"))
        else:
            results.append((page, True, "ok"))
    return results
