"""Write the generated data files out for the site to load."""

import datetime
import hashlib
import json
import os
import re

SITE_DIR = "candidate_profiles_site"
DATA_DIR = os.path.join(SITE_DIR, "data")
DATA_FILE = os.path.join(DATA_DIR, "profiles.js")
GEO_FILE = os.path.join(DATA_DIR, "geo.js")

# The scripts each page must load, in the order it must load them. The build
# never rewrites a page; it only reports when one has drifted out of step with
# the data it depends on.
#
# Order is the substantive part. Every generated file assigns a global, and
# the page modules read those globals as they initialise, so a page that
# loads its own module before the data renders an empty site with no error.
PAGE_REQUIREMENTS = {
    "index.html": (
        "assets/kyc.js",
        "data/profiles.js",
        "assets/kyc-profile.js",
        "assets/kyc-directory.js",
    ),
    "map.html": (
        "assets/kyc.js",
        "data/profiles.js",
        "data/geo.js",
        "assets/kyc-profile.js",
        "assets/kyc-map.js",
    ),
}

PAGES = tuple(PAGE_REQUIREMENTS)

_BANNER = """\
// Generated by build_profile_site.py - do not edit by hand.
// Source: {source}
// Built: {built}
"""


def _atomic_write(path, text):
    """Write *text* to *path* via a temp file so a crash cannot truncate it."""
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    os.replace(tmp, path)
    return len(text.encode("utf-8"))


def build_timestamp():
    """Build time, honouring ``SOURCE_DATE_EPOCH``.

    A fixed epoch makes the output byte-for-byte reproducible, which is what
    lets CI assert that a rebuild changes nothing.
    """
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    now = (
        datetime.datetime.fromtimestamp(int(epoch), datetime.timezone.utc)
        if epoch and epoch.isdigit()
        else datetime.datetime.now(datetime.timezone.utc)
    )
    return now.isoformat(timespec="seconds")


def _json(value):
    """Compact JSON that is safe to embed in a ``<script>`` element.

    A profile field containing ``</script>`` would otherwise close the tag
    early and break the page; ``<!--`` can start an HTML comment inside a
    classic script and swallow the rest of the file.
    """
    text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return text.replace("</", "<\\/").replace("<!--", "<\\!--")


def data_signature(profiles, races=None, summary=None):
    """A content hash of everything the build derives from the sources.

    Deliberately excludes the build timestamp. "Is the committed data still in
    sync with the CSVs?" and "when was this built?" are different questions,
    and answering the first by diffing whole files forced the second to be a
    lie: CI rebuilt with a fixed SOURCE_DATE_EPOCH, so keeping `git diff`
    quiet would have meant committing a 2001 timestamp and showing it to
    readers in the page footer as the freshness stamp.
    """
    payload = _json([profiles, races or [], summary or {}])
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


_SIGNATURE_RE = re.compile(r'"signature":"([0-9a-f]{64})"')


def read_signature(root=".", path=None):
    """The signature recorded in a generated file, or ``None``."""
    target = path or os.path.join(root, DATA_FILE)
    if not os.path.exists(target):
        return None
    with open(target, "r", encoding="utf-8") as handle:
        # The signature lives in the metadata line at the end of the file;
        # reading the whole 1 MB payload to find it would be wasteful.
        for line in handle:
            match = _SIGNATURE_RE.search(line)
            if match:
                return match.group(1)
    return None


def write_profiles(profiles, stats, root=".", races=None, summary=None):
    """Emit ``candidate_profiles_site/data/profiles.js``.

    A plain script assignment rather than JSON + ``fetch`` so the pages keep
    working when opened straight off disk - ``file://`` requests are blocked
    by CORS, but ``<script src>`` is not.
    """
    path = os.path.join(root, DATA_FILE)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    built = build_timestamp()
    meta = {"built": built, "counts": stats,
            "signature": data_signature(profiles, races, summary)}
    if summary:
        meta.update(summary)

    text = (
        _BANNER.format(source="the roster CSVs at the repository root", built=built)
        + f"// Profiles: {len(profiles)}\n"
        + f"window.legislatorsData = {_json(profiles)};\n"
        + f"window.kycRaces = {_json(races or [])};\n"
        + f"window.kycBuildMeta = {_json(meta)};\n"
    )
    return path, _atomic_write(path, text)


def write_geo(geo, root="."):
    """Emit ``candidate_profiles_site/data/geo.js``.

    Pre-rendered SVG path data for the map, so the page needs no mapping
    library at runtime. Same ``<script src>`` reasoning as the profiles file.
    """
    path = os.path.join(root, GEO_FILE)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    text = (
        _BANNER.format(source="us_atlas_states_topo.json", built=build_timestamp())
        + f"// States: {len(geo.get('states', {}))}\n"
        + f"window.kycGeo = {_json(geo)};\n"
        + 'window.kycGeoMeta = {"signature":"' + geo_signature(geo) + '"};\n'
    )
    return path, _atomic_write(path, text)


def geo_signature(geo):
    """Content hash of the map geometry, excluding the build timestamp."""
    return hashlib.sha256(_json(geo).encode("utf-8")).hexdigest()


def script_sources(html):
    """Every ``<script src="...">`` in *html*, in document order."""
    return re.findall(r'<script[^>]*\bsrc="([^"]+)"', html)


# ------------------------------------------------------------------ hostname

CNAME_FILE = os.path.join(SITE_DIR, "CNAME")

# Files that name the public hostname, and how to find it in each. GitHub
# Pages takes it from CNAME; everything else has to agree with that file or
# the site tells search engines and social networks it lives somewhere it
# does not. Six copies of a hostname across five files is precisely the kind
# of thing that drifts silently after a rename.
_HOST_REFERENCES = {
    os.path.join(SITE_DIR, "index.html"): r'rel="canonical" href="https://([^/"]+)',
    os.path.join(SITE_DIR, "map.html"): r'rel="canonical" href="https://([^/"]+)',
    os.path.join(SITE_DIR, "robots.txt"): r"Sitemap:\s*https://([^/\s]+)",
    os.path.join(SITE_DIR, "sitemap.xml"): r"<loc>https://([^/<]+)",
}


def canonical_host(root="."):
    """The hostname GitHub Pages will serve from, or ``None``."""
    path = os.path.join(root, CNAME_FILE)
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read().strip() or None


def check_hostname(root="."):
    """Report files whose hostname disagrees with CNAME.

    Returns a list of ``(file, ok, note)``.
    """
    expected = canonical_host(root)
    if expected is None:
        return [(CNAME_FILE, True, "no custom domain configured")]

    results = [(CNAME_FILE, True, expected)]
    for relative, pattern in _HOST_REFERENCES.items():
        path = os.path.join(root, relative)
        if not os.path.exists(path):
            results.append((relative, False, "missing"))
            continue
        with open(path, "r", encoding="utf-8") as handle:
            found = set(re.findall(pattern, handle.read()))
        if not found:
            results.append((relative, False, f"names no host; expected {expected}"))
        elif found != {expected}:
            results.append(
                (relative, False, f"names {', '.join(sorted(found))}; CNAME says {expected}")
            )
        else:
            results.append((relative, True, "ok"))
    return results


def check_pages(root="."):
    """Report which pages are wired up to the scripts they need.

    Returns a list of ``(page, ok, note)``.
    """
    results = []
    for page, required in PAGE_REQUIREMENTS.items():
        path = os.path.join(root, SITE_DIR, page)
        if not os.path.exists(path):
            results.append((page, False, "missing"))
            continue
        with open(path, "r", encoding="utf-8") as handle:
            loaded = script_sources(handle.read())

        problems = []
        missing = [src for src in required if src not in loaded]
        if missing:
            problems.append("does not load " + ", ".join(missing))

        present = [src for src in required if src in loaded]
        order = [loaded.index(src) for src in present]
        if order != sorted(order):
            problems.append(
                "scripts load out of order; expected " + " -> ".join(required)
            )

        for src in required:
            if src in loaded and not os.path.exists(
                os.path.join(root, SITE_DIR, *src.split("/"))
            ):
                problems.append(f"{src} is referenced but does not exist")

        results.append((page, not problems, "; ".join(problems) if problems else "ok"))
    return results
