"""Write the generated data files out for the site to load."""

import datetime
import json
import os
import re

SITE_DIR = "candidate_profiles_site"
DATA_DIR = os.path.join(SITE_DIR, "data")
DATA_FILE = os.path.join(DATA_DIR, "profiles.js")
GEO_FILE = os.path.join(DATA_DIR, "geo.js")

# The scripts each page must load, in the order it must load them. The build
# never rewrites a page; it only reports when one has drifted out of step with
# the data it depends on.
#
# Order is the substantive part. Every generated file assigns a global, and
# the page modules read those globals as they initialise, so a page that
# loads its own module before the data renders an empty site with no error.
PAGE_REQUIREMENTS = {
    "index.html": (
        "assets/kyc.js",
        "data/profiles.js",
        "assets/kyc-profile.js",
        "assets/kyc-directory.js",
    ),
    "map.html": (
        "assets/kyc.js",
        "data/profiles.js",
        "data/geo.js",
        "assets/kyc-profile.js",
        "assets/kyc-map.js",
    ),
}

PAGES = tuple(PAGE_REQUIREMENTS)

_BANNER = """\
// Generated by build_profile_site.py - do not edit by hand.
// Source: {source}
// Built: {built}
"""


def _atomic_write(path, text):
    """Write *text* to *path* via a temp file so a crash cannot truncate it."""
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    os.replace(tmp, path)
    return len(text.encode("utf-8"))


def build_timestamp():
    """Build time, honouring ``SOURCE_DATE_EPOCH``.

    A fixed epoch makes the output byte-for-byte reproducible, which is what
    lets CI assert that a rebuild changes nothing.
    """
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    now = (
        datetime.datetime.fromtimestamp(int(epoch), datetime.timezone.utc)
        if epoch and epoch.isdigit()
        else datetime.datetime.now(datetime.timezone.utc)
    )
    return now.isoformat(timespec="seconds")


def _json(value):
    """Compact JSON that is safe to embed in a ``<script>`` element.

    A profile field containing ``</script>`` would otherwise close the tag
    early and break the page; ``<!--`` can start an HTML comment inside a
    classic script and swallow the rest of the file.
    """
    text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return text.replace("</", "<\\/").replace("<!--", "<\\!--")


def write_profiles(profiles, stats, root=".", races=None, summary=None):
    """Emit ``candidate_profiles_site/data/profiles.js``.

    A plain script assignment rather than JSON + ``fetch`` so the pages keep
    working when opened straight off disk - ``file://`` requests are blocked
    by CORS, but ``<script src>`` is not.
    """
    path = os.path.join(root, DATA_FILE)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    built = build_timestamp()
    meta = {"built": built, "counts": stats}
    if summary:
        meta.update(summary)

    text = (
        _BANNER.format(source="the roster CSVs at the repository root", built=built)
        + f"// Profiles: {len(profiles)}\n"
        + f"window.legislatorsData = {_json(profiles)};\n"
        + f"window.kycRaces = {_json(races or [])};\n"
        + f"window.kycBuildMeta = {_json(meta)};\n"
    )
    return path, _atomic_write(path, text)


def write_geo(geo, root="."):
    """Emit ``candidate_profiles_site/data/geo.js``.

    Pre-rendered SVG path data for the map, so the page needs no mapping
    library at runtime. Same ``<script src>`` reasoning as the profiles file.
    """
    path = os.path.join(root, GEO_FILE)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    text = (
        _BANNER.format(source="us_atlas_states_topo.json", built=build_timestamp())
        + f"// States: {len(geo.get('states', {}))}\n"
        + f"window.kycGeo = {_json(geo)};\n"
    )
    return path, _atomic_write(path, text)


def script_sources(html):
    """Every ``<script src="...">`` in *html*, in document order."""
    return re.findall(r'<script[^>]*\bsrc="([^"]+)"', html)


def check_pages(root="."):
    """Report which pages are wired up to the scripts they need.

    Returns a list of ``(page, ok, note)``.
    """
    results = []
    for page, required in PAGE_REQUIREMENTS.items():
        path = os.path.join(root, SITE_DIR, page)
        if not os.path.exists(path):
            results.append((page, False, "missing"))
            continue
        with open(path, "r", encoding="utf-8") as handle:
            loaded = script_sources(handle.read())

        problems = []
        missing = [src for src in required if src not in loaded]
        if missing:
            problems.append("does not load " + ", ".join(missing))

        present = [src for src in required if src in loaded]
        order = [loaded.index(src) for src in present]
        if order != sorted(order):
            problems.append(
                "scripts load out of order; expected " + " -> ".join(required)
            )

        for src in required:
            if src in loaded and not os.path.exists(
                os.path.join(root, SITE_DIR, *src.split("/"))
            ):
                problems.append(f"{src} is referenced but does not exist")

        results.append((page, not problems, "; ".join(problems) if problems else "ok"))
    return results
